[project]
name = "assistant-service"
version = "0.1.0"
description = "LLM assistant service"
authors = [
    { name = "o-d-mitin-edu-mtuci-ru", email = "fazzil349@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aio-pika>=9.6.2",
    "google-genai>=2.10.0",
    "pydantic-settings>=2.14.2",
]

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
